  
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Grails

on: [push, pull_request]

jobs:
  deploy-to-tomcat:

    runs-on: grails

    strategy:
      fail-fast: false
      matrix:
        tomcat: [9.0.37, 8.5.57]
    env: 
      TOMCAT_VERSION: 9.0.37

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: dev war
      - name: Deploy to Tomcat
        run: cp build/libs/joinfaces-gradle-war-example.war apache-tomcat-${{ matrix.tomcat }}/webapps/
      - name: Verify Deployment
        run: |
          timeout --preserve-status 60s tail -f apache-tomcat-${{ matrix.tomcat }}/logs/catalina.out || true
          wget localhost:8080/joinfaces-gradle-war-example/index.xhtml
          grep "Hello from Spring" index.xhtml
