name: Generate WAR file and push it on Tomcat Server
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [11]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: WAR file + curl to Tomcat
        run: cd projet && chmod +x ./gradlew && ./gradlew assemble && cd build/libs && ls && curl -v -u admin:d2mprojet --insecure "https://172.16.100.68:8080/manager/text/undeploy?path=/isitech-0.1" && curl -u admin:d2mprojet -T  isitech-0.1.war "http://172.16.100.68:8080/manager/text/deploy?path=/isitech-0.1&update=true"
        
