name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: proactivehk/grails:2.5.6
    steps:
      - cd ./dgd
      - export APP_NAME=`cat application.properties | grep app.name | cut -f 2 -d =`
      - export APP_VERSION=`cat application.properties | grep app.version | cut -f 2 -d =`
      - echo "Building application $APP_NAME version $APP_VERSION"
      - grails test war
      - cd ./target
      - curl -v -u $tomcat_user:$tomcat_password --insecure "https://xxxxxxxxx/manager/text/undeploy?path=/$APP_NAME"
      - curl -v -u $tomcat_user:$tomcat_password --insecure -T $APP_NAME-$APP_VERSION.war "https://xxxxxxx/manager/text/deploy?path=/$APP_NAME&update=true"

